---
- hosts: dev
  vars:
    prompt: '\[\e[0;32m\][\u@\h]\[\e[0;30m\]$(__git_ps1 "#%s")\[\e[0m\] \w \[\e[0;32m\]\$\[\e[0m\] '
  tasks:
    - include: tasks/default.yml

- hosts: test
  vars:
    prompt: '\[\e[0;93m\][\u@\h]\[\e[0;30m\]$(__git_ps1 "#%s")\[\e[0m\] \w \[\e[0;93m\]\$\[\e[0m\] '
  tasks:
    - include: tasks/default.yml

- hosts: prod
  vars:
    prompt: '\[\e[0;31m\][\u@\h]\[\e[0;30m\]$(__git_ps1 "#%s")\[\e[0m\] \w \[\e[0;31m\]\$\[\e[0m\] '
  tasks:
    - include: tasks/default.yml

- hosts: staging
  vars:
    prompt: '\[\e[0;34m\][\u@\h]\[\e[0;30m\]$(__git_ps1 "#%s")\[\e[0m\] \w \[\e[0;34m\]\$\[\e[0m\] '
  tasks:
    - include: tasks/default.yml
