---
# install bash settings

- name: Copy .git-prompt.sh (git prompt in bash)
  copy: src=~/.git-prompt.sh dest=~/.git-prompt.sh

- name: Backup default .bash_profile
  command: cp -v ~/.bash_profile ~/.bash_profile.old
  ignore_errors: yes

- name: Copy new .bash_profile
  template: src=templates/bash_profile.j2 dest=~/.bash_profile mode=0640

- name: Backup default .bashrc
  command: cp -v ~/.bashrc ~/.bashrc.old
  ignore_errors: yes

- name: Copy new .bashrc
  template: src=templates/bashrc.j2 dest=~/.bashrc mode=0640

- name: Backup default .gitconfig
  command: cp -v ~/.gitconfig ~/.gitconfig.old
  ignore_errors: yes

- name: Copy .gitconfig
  copy: src=~/.gitconfig dest=~/.gitconfig

- name: Backup default .vimrc
  command: cp -v ~/.vimrc ~/.vimrc.old
  ignore_errors: yes

- name: Copy .vimrc
  copy: src=~/.vimrc dest=~/.vimrc

- name: Backup default .vim settings dir
  command: cp -rv ~/.vim ~/.vim.old
  ignore_errors: yes

- name: Copy .vim settings dir
  synchronize: 
    src: ~/.vim 
    dest: ~/
